
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: daudulislam/enrollmentsapi:v8
          ports:
            - containerPort: 80
          env:
            - name: RabbitMQ__HostName
              value: "rabbitmq"
            - name: RabbitMQ__Port
              value: "5672"
            - name: RabbitMQ__UserName
              value: "guest"
            - name: RabbitMQ__Password
              value: "guest"
            - name: ASPNETCORE_URLS
              value: http://+:80

apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
spec:
  selector: 
    app.kubernetes.io/name: k8s-app
  ports:
   - name: k8s-app
     protocol: TCP
     port: 8081
     targetPort: 80
  type: LoadBalancer
