apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: "user"
          - name: RABBITMQ_DEFAULT_PASS
            value: "mypass"
        ports:
          - containerPort: 5672   # RabbitMQ port
          - containerPort: 15672  # Management web interface
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp  # Name for the AMQP port
      port: 5672
      targetPort: 5672
    - name: management  # Name for the Management UI port
      port: 15672
      targetPort: 15672
